apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  releaseName: kyverno
  chart:
    spec:
      chart: ./charts/kyverno
      sourceRef:
        kind: GitRepository
        name: kyverno
        namespace: flux-system
  interval: 15m
  install:
    remediation:
      retries: 2
  valuesFrom:
    - kind: ConfigMap
      name: kyverno-generic-values
    - kind: ConfigMap
      name: kyverno-environment-values