apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-helm
  namespace: kyverno
spec:
  project: default
  source:
    chart: kyverno
    repoURL:  https://kyverno.github.io/kyverno/
    targetRevision: 3.1.0
    helm:
      releaseName: kyverno
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kyverno
